name: mldd25
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - biopython=1.85
  - black=25.1.0
  - bokeh=3.6.3
  - chembl_webresource_client=0.10.9
  - isort=6.0.1
  - jupyter=1.1.1
  - matplotlib=3.10.1
  - notebook=7.3.2
  - numpy=1.26.4
  - openbabel=3.1.1
  - pandas=2.1.4
  - pip=25.0.1
  - prolif=2.0.3
  - py3dmol=2.4.2
  - pyg=2.6.1
  - pymol-open-source=3.0.0
  - pypdb=2.4
  - pytdc=0.3.8
  - pytest=8.3.5
  - python=3.12.9
  - pytorch=2.4.1
  - pytorch-lightning=2.5.0.post0
  - pyyaml=6.0.2
  - qvina=2.1.0
  - rdkit=2023.09.6
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - smina=2020.12.10
  - streamlit=1.42.2
  - tqdm=4.67.1
  - yaml=0.2.5
